include $(sort $(wildcard $(BR2_EXTERNAL_SPINAL_SAXON_PATH)/package/*/*.mk))

ifndef SAXON_CPU_COUNT
$(error SAXON_CPU_COUNT is not set)
endif

ifndef SAXON_FPU
$(error SAXON_FPU is not set)
endif

ifndef SDRAM_SIZE
$(error SDRAM_SIZE is not set)
endif

HOST_CFLAGS+=-DSAXON_CPU_COUNT=$(SAXON_CPU_COUNT)
HOST_CFLAGS+=-DSAXON_FPU=$(SAXON_FPU)
HOST_CFLAGS+=-DSDRAM_SIZE=$(SDRAM_SIZE)
HOST_CFLAGS+=-I$(BR2_EXTERNAL_SPINAL_SAXON_PATH)

MPG123_CPU=generic_nofpu

#XLIB_LIBXSHMFENCE_CFLAGS+="-DSYS_futex=SYS_futex_time64"
TARGET_CFLAGS+="-DSYS_futex=SYS_futex_time64"
#TARGET_CFLAGS+="-D__NR_io_getevents=4"



ifeq ($(BR2_PACKAGE_VEXRISCV_AES),y)
LIBRESSL_CONF_OPTS+=-DVEXRISCV_AES=ON
endif
