define OPENSBI_VEX_PLATFORM_COPY
	cp -r $(BR2_EXTERNAL_VEXRISCV_SAXON_PATH)/package/opensbi/platform $(BUILD_DIR)/opensbi-$(OPENSBI_VERSION) 
endef

OPENSBI_PRE_BUILD_HOOKS += OPENSBI_VEX_PLATFORM_COPY

